agent.sources = r1
agent.sinks = k1
agent.channels = c1


agent.sources.r1.type = netcat
agent.sources.r1.bind = 0.0.0.0
agent.sources.r1.port = 44444


agent.sinks.k1.type = hbase
agent.sinks.k1.table = events
agent.sinks.k1.columnFamily = cf
agent.sinks.k1.serializer = org.apache.flume.sink.hbase.SimpleHbaseEventSerializer


agent.channels.c1.type = memory
agent.channels.c1.capacity = 1000
agent.channels.c1.transactionCapacity = 100


agent.sources.r1.channels = c1
agent.sinks.k1.channel = c1